version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres12
    ports:
      - "5432:7777"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: